apiVersion: v1
kind: BuildConfig
metadata:
  name: springBootMonitoring55
  labels:
    app: springBootMonitoring56
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "springBootMonitoring56", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
  - type: GitHub
    github:
      secret: a04aabf8d0002f77
  resources:
    limits:
      cpu: 80m
      memory: 512Mi
    requests:
      cpu: 70m
      memory: 256Mi
      volumeMounts:
        - name: default-token-2lhkq
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
         node {
           stage('buildImage'){
             openshiftBuild(buildConfig: 'springBootMonitoring56', showBuildLogs: 'true')
           }
           stage('deployApplication'){
             openshiftDeploy(deploymentConfig: 'springBootMonitoring56')
           }
         }
